# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NOTVUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=32, unique=True, verbose_name='Электронная почта')),
                ('avatar', models.ImageField(blank=True, upload_to='images/%Y/%m', verbose_name='Аватар')),
                ('first_name', models.CharField(blank=True, max_length=16, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=32, verbose_name='Фамилия')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Университет/Подразделение')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Является администратором?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является суперпользователем?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
