# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notvuser',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='notvuser',
            name='tel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Университет/Подразделение'),
        ),
        migrations.AlterField(
            model_name='notvuser',
            name='department',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Университет/Подразделение'),
        ),
    ]
