# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notvuser',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
