# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notvuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notvuser',
            name='department',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='notvuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='notvuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Фамилия'),
        ),
    ]
