# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160401_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notvuser',
            name='tel',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон'),
        ),
    ]
