# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160401_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='notvuser',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 4, 1, 8, 42, 7, 76930, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notvuser',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплатил'),
        ),
        migrations.AddField(
            model_name='notvuser',
            name='status',
            field=models.CharField(choices=[('online', 'Заочно'), ('offline', 'Очно')], default='offline', max_length=7, verbose_name='Статус'),
        ),
    ]
